spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://3.34.188.69:3306/eta?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: hunsung
    password: gustmd12
  web:
    cors:
      allowed-origins: http://localhost:3000
  jpa:
    hibernate:
      ddl-auto: update
